### PR TITLE
Fix bug investment related variables

### LINKED ISSUE #1247: [Bug] Assets with investment method `none` can have investments
### Description

Currently we only check investable for create the variables, so we can have investment variables even if the investment method is set to `none`, here is the snnipet:

https://github.com/TulipaEnergy/TulipaEnergyModel.jl/blob/e0458292c25c9d2ec6e92ade6ecc0ca748f65990/src/sql/create-variables.sql#L245-L247

This needs to be checked also for the storage investment and flow investment.

### Package Version

0.16.0

### Julia Version

1.1

### Reproduction steps

In the multi-year investment case study asests to `none` and the ones investable will have investments.

### Relevant log output

```shell

```

### Operating System

_No response_

### PR DESCRIPTION
**Pull request by gnawin**
**Model changes:**
- Ensure `var_assets_investment` are only created for **simple or compact** method
- Ensure `var_assets_decommission` are only created for **simple or compact** method
- Ensure `var_assets_investment_energy` are only created for **simple** method
- Ensure `var_assets_decommission_energy` are only created for **simple** method

**Test changes**
- `Tiny` case has `investable=true` for `investment_method=none`. It is corrected in this PR. Hence the test change.
- Almost all other cases have such conflicts (except for Multi-year!), but the results do not change. So I updated all MPS files.

## Related issues

Closes #1247 

## Checklist

- [x] I am following the [contributing guidelines](https://github.com/TulipaEnergy/TulipaEnergyModel.jl/blob/main/docs/src/90-contributing.md)

- [x] Tests are passing
- [x] Lint workflow is passing
- [x] Docs were updated and workflow is passing

### CODE REVIEW

File: src/sql/create-variables.sql [hunk 1]
```diff
@@ -269,6 +270,7 @@ from
     left join asset on asset.asset = asset_both.asset
 where
     asset_both.decommissionable
+    and asset.investment_method in ('simple', 'compact')
```
Comment (datejada) [inline src/sql/create-variables.sql:273]:
```suggestion
```

**Review by datejada — COMMENTED** [review]
Hi @gnawin Thanks for the PR. I am not sure about having the decommission variable not created when `investment_method` is `none`; because, you can have existing units (initial units) that you want the model to decide to decommission or not, but you don't want to have investment variables. For example, and old CCGT technology, that you don't want to invest more, but you want to know if it is better to decommission or not. Is it clear?

Also, because the `investment_method` should affect only investment variables not decommission variables.

What do you think?

**Comment by gnawin** [comment]
> Hi @gnawin Thanks for the PR. I am not sure about having the decommission variable not created when `investment_method` is `none`; because, you can have existing units (initial units) that you want the model to decide to decommission or not, but you don't want to have investment variables. For example, and old CCGT technology, that you don't want to invest more, but you want to know if it is better to decommission or not. Is it clear?
> 
> Also, because the `investment_method` should affect only investment variables not decommission variables.
> 
> What do you think?

I see your point. 

In my mind, having `investment_method = none` means you would like to keep the initial units and do nothing with it. In that sense `investment_method` is used as a general method for both investment and decommissions. If you want decomissions, you need to set `investment_method != none` and `decommission=true`,  
The reason for this logic is decommission variables are directly related to the investment variables. I.e., the decom variables are different when you have `simple` or `compact`. 

That being said, I can see if it feels a bit weird to call it `investment_method` while it affects both investment and decom variables. Especially in the future when we have retrofits, but that one we still need to discuss, and I think we should come back to this after that.

**Comment by datejada** [comment]
> > Hi @gnawin Thanks for the PR. I am not sure about having the decommission variable not created when `investment_method` is `none`; because, you can have existing units (initial units) that you want the model to decide to decommission or not, but you don't want to have investment variables. For example, and old CCGT technology, that you don't want to invest more, but you want to know if it is better to decommission or not. Is it clear?
> > Also, because the `investment_method` should affect only investment variables not decommission variables.
> > What do you think?
> 
> I see your point.
> 
> In my mind, having `investment_method = none` means you would like to keep the initial units and do nothing with it. In that sense `investment_method` is used as a general method for both investment and decommissions. If you want decomissions, you need to set `investment_method != none` and `decommission=true`, The reason for this logic is decommission variables are directly related to the investment methods. I.e., the decom variables are different when you have `simple` or `compact`.
> 
> That being said, I can see if it feels a bit weird to call it `investment_method` while it affects both investment and decom variables. Especially in the future when we have retrofits, but that one we still need to discuss, and I think we should come back to this after that.

I see, okay, that explanation is clear, then. However, the name `investment_method` is not ideal, as it misleads users (or at least it did to me). Would you mind creating an issue to modify that name?

**Comment by gnawin** [comment]
@datejada  Would you mind having a look again? I only changed `ccgt` to `simple` in Tiny and `Tinier`, so the objective values do not change anymore. 
All MPS files change because of the inconsistency in data, they will be tackled in #1249 so the MPS files will change again with consistent data. And since this is a bug, I will do it separate from this issue.
Thank you!
