### PR TITLE
Fix objective function calculation of the variable cost

### LINKED ISSUE #300: The variable cost of flow does not get multiplied by the partition range
### Description

Hi all,

I have built the case NL & BE. When I implement the uniform partition 2 on all BE-related assets and flows, I get 2/3 of the objective value, compared with when I have both in uniform partition 1.

I think this is because, in the objective, the variable cost of the flow does not get multiplied by the timesteps it covers. So when we have 1/2 of the flow variables in one of the two countries, we get 2/3 of the objective value. 

Is there any way to fix this? I would like to have an objective that is constant with time partition (counting every time step regardless of the partition).

[input_NLBE_1h2h_27Nov2023.zip](https://github.com/TulipaEnergy/TulipaEnergyModel.jl/files/13480699/input_NLBE_1h2h_27Nov2023.zip)
[input_NLBE_27Nov2023.zip](https://github.com/TulipaEnergy/TulipaEnergyModel.jl/files/13480700/input_NLBE_27Nov2023.zip)

### Reproduction steps

```bash
1. Run both cases "input_NLBE" and "input_NLBE_1h2h".
2. Notice that the objective value differs significantly, which should not happen.
```

### Logs

```bash
flows_variable_cost = @expression(
        model,
        sum(
            representative_periods[rp].weight *
            graph[u, v].variable_cost *
            flow[(u, v), rp, B_flow] for (u, v) ∈ F, rp ∈ RP,
            B_flow ∈ graph[u, v].partitions[rp]
        )
    )

Can we multiply here with the length of B_flow?
```

### OS

_No response_

### PR DESCRIPTION
**Pull request by datejada**
# Pull request details

## Describe the changes made in this pull request

Add the duration of the flow to the calculation of the variable cost in the objective function.

## List of related issues or pull requests

Closes #300 

## Collaboration confirmation

As a contributor I confirm

- [x] I read and followed the instructions in README.dev.md
- [x] The documentation is up to date with the changes introduced in this Pull Request (or NA)
- [x] Tests are passing
- [x] Lint is passing

### CODE REVIEW

File: src/model.jl [hunk 1]
```diff
@@ -74,8 +74,8 @@ function create_model(
         sum(
             representative_periods[rp].weight *
             graph[u, v].variable_cost *
-            flow[(u, v), rp, B_flow] for (u, v) ∈ F, rp ∈ RP,
-            B_flow ∈ graph[u, v].partitions[rp]
+            flow[(u, v), rp, B_flow] *
+            length(B_flow) for (u, v) ∈ F, rp ∈ RP, B_flow ∈ graph[u, v].partitions[rp]
```
Comment (abelsiqueira) [inline src/model.jl:78]: You need the resolution too, right?

Comment (datejada) [reply src/model.jl:78]: Yes, I agree. Thank you for pointing that out

**Review by abelsiqueira — APPROVED** [review]
Thanks
